"""update model

Revision ID: 3f950d056e47
Revises: e87f70d1ff8f
Create Date: 2023-12-18 14:51:54.573636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f950d056e47'
down_revision = 'e87f70d1ff8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('source_id', sa.String(length=256), nullable=True))
    op.drop_column('recipes', 'subreddit_name_prefixed')
    op.drop_column('recipes', 'reddit_post_id')
    op.drop_column('recipes', 'mealdb_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('mealdb_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('reddit_post_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('subreddit_name_prefixed', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'source_id')
    # ### end Alembic commands ###
