"""add-subreddit-field

Revision ID: e87f70d1ff8f
Revises: 196ac270d56d
Create Date: 2023-06-17 23:12:59.819698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87f70d1ff8f'
down_revision = '196ac270d56d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('subreddit_name_prefixed', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'subreddit_name_prefixed')
    # ### end Alembic commands ###
