"""update user model

Revision ID: 506b33040f80
Revises: 39ada159faf2
Create Date: 2022-07-17 20:13:41.893566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506b33040f80'
down_revision = '39ada159faf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_normalized', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email_normalized'), 'users', ['email_normalized'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_normalized'), table_name='users')
    op.drop_column('users', 'email_normalized')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
